site_name: PyEyesWeb

plugins:
  - gen-files:
      scripts:
        - gen_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths: [PyEyesWeb]            # root, since "core" is directly there
          options:
            docstring_style: numpy
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.keys
#  - toc:
#      permalink: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
#    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Examples: examples.md
  - API: API/
