site_name: PyEyesWeb

plugins:
  - gen-files:
      scripts:
        - gen_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths: [PyEyesWeb]            # root, since "core" is directly there
          options:
            docstring_style: numpy
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - API: API/index.md
  - Examples: examples.md
