site_name: PyEyesWeb
repo_url: https://github.com/InfoMusCP/PyEyesWeb
site_url: https://github.com/InfoMusCP/PyEyesWeb

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - API: api.md
  - Examples: examples.md

